[2024-06-30T02:34:35.485+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-30T02:34:35.518+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dag.report_task scheduled__2024-06-29T02:32:57.600741+00:00 [queued]>
[2024-06-30T02:34:35.561+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dag.report_task scheduled__2024-06-29T02:32:57.600741+00:00 [queued]>
[2024-06-30T02:34:35.563+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-06-30T02:34:35.640+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): report_task> on 2024-06-29 02:32:57.600741+00:00
[2024-06-30T02:34:35.658+0000] {standard_task_runner.py:57} INFO - Started process 313 to run task
[2024-06-30T02:34:35.670+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_dag', 'report_task', 'scheduled__2024-06-29T02:32:57.600741+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpk_nzunhv']
[2024-06-30T02:34:35.679+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask report_task
[2024-06-30T02:34:35.727+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-30T02:34:35.878+0000] {task_command.py:410} INFO - Running <TaskInstance: example_dag.report_task scheduled__2024-06-29T02:32:57.600741+00:00 [running]> on host a6e3ed8ccea2
[2024-06-30T02:34:35.923+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-30T02:34:36.242+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_dag' AIRFLOW_CTX_TASK_ID='report_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T02:32:57.600741+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T02:32:57.600741+00:00'
[2024-06-30T02:34:36.265+0000] {logging_mixin.py:150} INFO - Daily Loan Summary Report - 2024-06-30

Category: Auto
  Total Loans: 4
  Average Loan Amount: $22000.00
  Average Interest Rate: 6.02%

Category: Business
  Total Loans: 4
  Average Loan Amount: $27500.00
  Average Interest Rate: 5.05%

Category: Education
  Total Loans: 4
  Average Loan Amount: $32000.00
  Average Interest Rate: 5.00%

Category: Home
  Total Loans: 4
  Average Loan Amount: $18000.00
  Average Interest Rate: 4.60%

Category: Personal
  Total Loans: 4
  Average Loan Amount: $12750.00
  Average Interest Rate: 5.25%
[2024-06-30T02:34:36.296+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.4p1)
[2024-06-30T02:34:36.468+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-06-30T02:34:37.256+0000] {sftp.py:169} INFO - [chan 0] Opened sftp connection (server version 3)
[2024-06-30T02:34:37.261+0000] {sftp.py:169} INFO - [chan 0] sftp session closed.
[2024-06-30T02:34:37.264+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/report.py", line 74, in generate_daily_report
    upload_report_to_sftp(report_path)
  File "/opt/airflow/dags/utils/report.py", line 79, in upload_report_to_sftp
    sftp.cwd(report_directory)
  File "/home/airflow/.local/lib/python3.7/site-packages/pysftp/__init__.py", line 524, in chdir
    self._sftp.chdir(remotepath)
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 659, in chdir
    if not stat.S_ISDIR(self.stat(path).st_mode):
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 903, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
[2024-06-30T02:34:37.315+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=example_dag, task_id=report_task, execution_date=20240629T023257, start_date=20240630T023435, end_date=20240630T023437
[2024-06-30T02:34:37.373+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 15 for task report_task ([Errno 2] No such file; 313)
[2024-06-30T02:34:37.403+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-06-30T02:34:37.471+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
